// <auto-generated/>
using System.Threading.Tasks;
namespace MonoGameLibrary.TinyECS;
public partial class Registry
{

  public delegate void QueryDelegate<T1>(ref T1 c1)
      where T1 : struct
;

  public void Query<T1>(QueryDelegate<T1> action)
      where T1 : struct
  {
      var store1 = Assure<T1>();

      var leader = 0;
      var leaderCount = store1.Count;

      switch (leader)
      {
          case 0:
          {
              var dense = store1.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  action(ref store1.GetByIndex(i)  );
              }

              break;
          }
      }
  }
  public void QueryParallel<T1>(QueryDelegate<T1> action)
      where T1 : struct
  {
      var store1 = Assure<T1>();

      var leader = 0;
      var leaderCount = store1.Count;

      switch (leader)
      {
          case 0:
          {
              var dense = store1.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  action(ref store1.GetByIndex(i)  );
              });

              break;
          }
      }
  }
  public delegate void QueryDelegate<T1, T2>(ref T1 c1, ref T2 c2)
      where T1 : struct
      where T2 : struct
;

  public void Query<T1, T2>(QueryDelegate<T1, T2> action)
      where T1 : struct
      where T2 : struct
  {
      var store1 = Assure<T1>();
      var store2 = Assure<T2>();

      var leader = 0;
      var leaderCount = store1.Count;

      if (store2.Count < leaderCount)
      {
          leader = 1;
          leaderCount = store2.Count;
      }

      switch (leader)
      {
          case 0:
          {
              var dense = store1.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store2.TryGetIndex(entity, out var index2)) continue;

                  action(ref store1.GetByIndex(i), ref store2.GetByIndex(index2)  );
              }

              break;
          }
          case 1:
          {
              var dense = store2.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(i)  );
              }

              break;
          }
      }
  }
  public void QueryParallel<T1, T2>(QueryDelegate<T1, T2> action)
      where T1 : struct
      where T2 : struct
  {
      var store1 = Assure<T1>();
      var store2 = Assure<T2>();

      var leader = 0;
      var leaderCount = store1.Count;

      if (store2.Count < leaderCount)
      {
          leader = 1;
          leaderCount = store2.Count;
      }

      switch (leader)
      {
          case 0:
          {
              var dense = store1.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store2.TryGetIndex(entity, out var index2)) return;

                  action(ref store1.GetByIndex(i), ref store2.GetByIndex(index2)  );
              });

              break;
          }
          case 1:
          {
              var dense = store2.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(i)  );
              });

              break;
          }
      }
  }
  public delegate void QueryDelegate<T1, T2, T3>(ref T1 c1, ref T2 c2, ref T3 c3)
      where T1 : struct
      where T2 : struct
      where T3 : struct
;

  public void Query<T1, T2, T3>(QueryDelegate<T1, T2, T3> action)
      where T1 : struct
      where T2 : struct
      where T3 : struct
  {
      var store1 = Assure<T1>();
      var store2 = Assure<T2>();
      var store3 = Assure<T3>();

      var leader = 0;
      var leaderCount = store1.Count;

      if (store2.Count < leaderCount)
      {
          leader = 1;
          leaderCount = store2.Count;
      }

      if (store3.Count < leaderCount)
      {
          leader = 2;
          leaderCount = store3.Count;
      }

      switch (leader)
      {
          case 0:
          {
              var dense = store1.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;

                  action(ref store1.GetByIndex(i), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3)  );
              }

              break;
          }
          case 1:
          {
              var dense = store2.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(i), ref store3.GetByIndex(index3)  );
              }

              break;
          }
          case 2:
          {
              var dense = store3.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(i)  );
              }

              break;
          }
      }
  }
  public void QueryParallel<T1, T2, T3>(QueryDelegate<T1, T2, T3> action)
      where T1 : struct
      where T2 : struct
      where T3 : struct
  {
      var store1 = Assure<T1>();
      var store2 = Assure<T2>();
      var store3 = Assure<T3>();

      var leader = 0;
      var leaderCount = store1.Count;

      if (store2.Count < leaderCount)
      {
          leader = 1;
          leaderCount = store2.Count;
      }

      if (store3.Count < leaderCount)
      {
          leader = 2;
          leaderCount = store3.Count;
      }

      switch (leader)
      {
          case 0:
          {
              var dense = store1.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;

                  action(ref store1.GetByIndex(i), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3)  );
              });

              break;
          }
          case 1:
          {
              var dense = store2.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(i), ref store3.GetByIndex(index3)  );
              });

              break;
          }
          case 2:
          {
              var dense = store3.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(i)  );
              });

              break;
          }
      }
  }
  public delegate void QueryDelegate<T1, T2, T3, T4>(ref T1 c1, ref T2 c2, ref T3 c3, ref T4 c4)
      where T1 : struct
      where T2 : struct
      where T3 : struct
      where T4 : struct
;

  public void Query<T1, T2, T3, T4>(QueryDelegate<T1, T2, T3, T4> action)
      where T1 : struct
      where T2 : struct
      where T3 : struct
      where T4 : struct
  {
      var store1 = Assure<T1>();
      var store2 = Assure<T2>();
      var store3 = Assure<T3>();
      var store4 = Assure<T4>();

      var leader = 0;
      var leaderCount = store1.Count;

      if (store2.Count < leaderCount)
      {
          leader = 1;
          leaderCount = store2.Count;
      }

      if (store3.Count < leaderCount)
      {
          leader = 2;
          leaderCount = store3.Count;
      }

      if (store4.Count < leaderCount)
      {
          leader = 3;
          leaderCount = store4.Count;
      }

      switch (leader)
      {
          case 0:
          {
              var dense = store1.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;

                  action(ref store1.GetByIndex(i), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4)  );
              }

              break;
          }
          case 1:
          {
              var dense = store2.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(i), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4)  );
              }

              break;
          }
          case 2:
          {
              var dense = store3.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(i), ref store4.GetByIndex(index4)  );
              }

              break;
          }
          case 3:
          {
              var dense = store4.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(i)  );
              }

              break;
          }
      }
  }
  public void QueryParallel<T1, T2, T3, T4>(QueryDelegate<T1, T2, T3, T4> action)
      where T1 : struct
      where T2 : struct
      where T3 : struct
      where T4 : struct
  {
      var store1 = Assure<T1>();
      var store2 = Assure<T2>();
      var store3 = Assure<T3>();
      var store4 = Assure<T4>();

      var leader = 0;
      var leaderCount = store1.Count;

      if (store2.Count < leaderCount)
      {
          leader = 1;
          leaderCount = store2.Count;
      }

      if (store3.Count < leaderCount)
      {
          leader = 2;
          leaderCount = store3.Count;
      }

      if (store4.Count < leaderCount)
      {
          leader = 3;
          leaderCount = store4.Count;
      }

      switch (leader)
      {
          case 0:
          {
              var dense = store1.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;

                  action(ref store1.GetByIndex(i), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4)  );
              });

              break;
          }
          case 1:
          {
              var dense = store2.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(i), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4)  );
              });

              break;
          }
          case 2:
          {
              var dense = store3.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(i), ref store4.GetByIndex(index4)  );
              });

              break;
          }
          case 3:
          {
              var dense = store4.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(i)  );
              });

              break;
          }
      }
  }
  public delegate void QueryDelegate<T1, T2, T3, T4, T5>(ref T1 c1, ref T2 c2, ref T3 c3, ref T4 c4, ref T5 c5)
      where T1 : struct
      where T2 : struct
      where T3 : struct
      where T4 : struct
      where T5 : struct
;

  public void Query<T1, T2, T3, T4, T5>(QueryDelegate<T1, T2, T3, T4, T5> action)
      where T1 : struct
      where T2 : struct
      where T3 : struct
      where T4 : struct
      where T5 : struct
  {
      var store1 = Assure<T1>();
      var store2 = Assure<T2>();
      var store3 = Assure<T3>();
      var store4 = Assure<T4>();
      var store5 = Assure<T5>();

      var leader = 0;
      var leaderCount = store1.Count;

      if (store2.Count < leaderCount)
      {
          leader = 1;
          leaderCount = store2.Count;
      }

      if (store3.Count < leaderCount)
      {
          leader = 2;
          leaderCount = store3.Count;
      }

      if (store4.Count < leaderCount)
      {
          leader = 3;
          leaderCount = store4.Count;
      }

      if (store5.Count < leaderCount)
      {
          leader = 4;
          leaderCount = store5.Count;
      }

      switch (leader)
      {
          case 0:
          {
              var dense = store1.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;

                  action(ref store1.GetByIndex(i), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5)  );
              }

              break;
          }
          case 1:
          {
              var dense = store2.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(i), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5)  );
              }

              break;
          }
          case 2:
          {
              var dense = store3.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(i), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5)  );
              }

              break;
          }
          case 3:
          {
              var dense = store4.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(i), ref store5.GetByIndex(index5)  );
              }

              break;
          }
          case 4:
          {
              var dense = store5.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(i)  );
              }

              break;
          }
      }
  }
  public void QueryParallel<T1, T2, T3, T4, T5>(QueryDelegate<T1, T2, T3, T4, T5> action)
      where T1 : struct
      where T2 : struct
      where T3 : struct
      where T4 : struct
      where T5 : struct
  {
      var store1 = Assure<T1>();
      var store2 = Assure<T2>();
      var store3 = Assure<T3>();
      var store4 = Assure<T4>();
      var store5 = Assure<T5>();

      var leader = 0;
      var leaderCount = store1.Count;

      if (store2.Count < leaderCount)
      {
          leader = 1;
          leaderCount = store2.Count;
      }

      if (store3.Count < leaderCount)
      {
          leader = 2;
          leaderCount = store3.Count;
      }

      if (store4.Count < leaderCount)
      {
          leader = 3;
          leaderCount = store4.Count;
      }

      if (store5.Count < leaderCount)
      {
          leader = 4;
          leaderCount = store5.Count;
      }

      switch (leader)
      {
          case 0:
          {
              var dense = store1.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;

                  action(ref store1.GetByIndex(i), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5)  );
              });

              break;
          }
          case 1:
          {
              var dense = store2.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(i), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5)  );
              });

              break;
          }
          case 2:
          {
              var dense = store3.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(i), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5)  );
              });

              break;
          }
          case 3:
          {
              var dense = store4.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(i), ref store5.GetByIndex(index5)  );
              });

              break;
          }
          case 4:
          {
              var dense = store5.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(i)  );
              });

              break;
          }
      }
  }
  public delegate void QueryDelegate<T1, T2, T3, T4, T5, T6>(ref T1 c1, ref T2 c2, ref T3 c3, ref T4 c4, ref T5 c5, ref T6 c6)
      where T1 : struct
      where T2 : struct
      where T3 : struct
      where T4 : struct
      where T5 : struct
      where T6 : struct
;

  public void Query<T1, T2, T3, T4, T5, T6>(QueryDelegate<T1, T2, T3, T4, T5, T6> action)
      where T1 : struct
      where T2 : struct
      where T3 : struct
      where T4 : struct
      where T5 : struct
      where T6 : struct
  {
      var store1 = Assure<T1>();
      var store2 = Assure<T2>();
      var store3 = Assure<T3>();
      var store4 = Assure<T4>();
      var store5 = Assure<T5>();
      var store6 = Assure<T6>();

      var leader = 0;
      var leaderCount = store1.Count;

      if (store2.Count < leaderCount)
      {
          leader = 1;
          leaderCount = store2.Count;
      }

      if (store3.Count < leaderCount)
      {
          leader = 2;
          leaderCount = store3.Count;
      }

      if (store4.Count < leaderCount)
      {
          leader = 3;
          leaderCount = store4.Count;
      }

      if (store5.Count < leaderCount)
      {
          leader = 4;
          leaderCount = store5.Count;
      }

      if (store6.Count < leaderCount)
      {
          leader = 5;
          leaderCount = store6.Count;
      }

      switch (leader)
      {
          case 0:
          {
              var dense = store1.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;

                  action(ref store1.GetByIndex(i), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6)  );
              }

              break;
          }
          case 1:
          {
              var dense = store2.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(i), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6)  );
              }

              break;
          }
          case 2:
          {
              var dense = store3.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(i), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6)  );
              }

              break;
          }
          case 3:
          {
              var dense = store4.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(i), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6)  );
              }

              break;
          }
          case 4:
          {
              var dense = store5.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(i), ref store6.GetByIndex(index6)  );
              }

              break;
          }
          case 5:
          {
              var dense = store6.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(i)  );
              }

              break;
          }
      }
  }
  public void QueryParallel<T1, T2, T3, T4, T5, T6>(QueryDelegate<T1, T2, T3, T4, T5, T6> action)
      where T1 : struct
      where T2 : struct
      where T3 : struct
      where T4 : struct
      where T5 : struct
      where T6 : struct
  {
      var store1 = Assure<T1>();
      var store2 = Assure<T2>();
      var store3 = Assure<T3>();
      var store4 = Assure<T4>();
      var store5 = Assure<T5>();
      var store6 = Assure<T6>();

      var leader = 0;
      var leaderCount = store1.Count;

      if (store2.Count < leaderCount)
      {
          leader = 1;
          leaderCount = store2.Count;
      }

      if (store3.Count < leaderCount)
      {
          leader = 2;
          leaderCount = store3.Count;
      }

      if (store4.Count < leaderCount)
      {
          leader = 3;
          leaderCount = store4.Count;
      }

      if (store5.Count < leaderCount)
      {
          leader = 4;
          leaderCount = store5.Count;
      }

      if (store6.Count < leaderCount)
      {
          leader = 5;
          leaderCount = store6.Count;
      }

      switch (leader)
      {
          case 0:
          {
              var dense = store1.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;

                  action(ref store1.GetByIndex(i), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6)  );
              });

              break;
          }
          case 1:
          {
              var dense = store2.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(i), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6)  );
              });

              break;
          }
          case 2:
          {
              var dense = store3.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(i), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6)  );
              });

              break;
          }
          case 3:
          {
              var dense = store4.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(i), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6)  );
              });

              break;
          }
          case 4:
          {
              var dense = store5.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(i), ref store6.GetByIndex(index6)  );
              });

              break;
          }
          case 5:
          {
              var dense = store6.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(i)  );
              });

              break;
          }
      }
  }
  public delegate void QueryDelegate<T1, T2, T3, T4, T5, T6, T7>(ref T1 c1, ref T2 c2, ref T3 c3, ref T4 c4, ref T5 c5, ref T6 c6, ref T7 c7)
      where T1 : struct
      where T2 : struct
      where T3 : struct
      where T4 : struct
      where T5 : struct
      where T6 : struct
      where T7 : struct
;

  public void Query<T1, T2, T3, T4, T5, T6, T7>(QueryDelegate<T1, T2, T3, T4, T5, T6, T7> action)
      where T1 : struct
      where T2 : struct
      where T3 : struct
      where T4 : struct
      where T5 : struct
      where T6 : struct
      where T7 : struct
  {
      var store1 = Assure<T1>();
      var store2 = Assure<T2>();
      var store3 = Assure<T3>();
      var store4 = Assure<T4>();
      var store5 = Assure<T5>();
      var store6 = Assure<T6>();
      var store7 = Assure<T7>();

      var leader = 0;
      var leaderCount = store1.Count;

      if (store2.Count < leaderCount)
      {
          leader = 1;
          leaderCount = store2.Count;
      }

      if (store3.Count < leaderCount)
      {
          leader = 2;
          leaderCount = store3.Count;
      }

      if (store4.Count < leaderCount)
      {
          leader = 3;
          leaderCount = store4.Count;
      }

      if (store5.Count < leaderCount)
      {
          leader = 4;
          leaderCount = store5.Count;
      }

      if (store6.Count < leaderCount)
      {
          leader = 5;
          leaderCount = store6.Count;
      }

      if (store7.Count < leaderCount)
      {
          leader = 6;
          leaderCount = store7.Count;
      }

      switch (leader)
      {
          case 0:
          {
              var dense = store1.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;
                  if (!store7.TryGetIndex(entity, out var index7)) continue;

                  action(ref store1.GetByIndex(i), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7)  );
              }

              break;
          }
          case 1:
          {
              var dense = store2.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;
                  if (!store7.TryGetIndex(entity, out var index7)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(i), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7)  );
              }

              break;
          }
          case 2:
          {
              var dense = store3.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;
                  if (!store7.TryGetIndex(entity, out var index7)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(i), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7)  );
              }

              break;
          }
          case 3:
          {
              var dense = store4.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;
                  if (!store7.TryGetIndex(entity, out var index7)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(i), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7)  );
              }

              break;
          }
          case 4:
          {
              var dense = store5.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;
                  if (!store7.TryGetIndex(entity, out var index7)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(i), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7)  );
              }

              break;
          }
          case 5:
          {
              var dense = store6.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  if (!store7.TryGetIndex(entity, out var index7)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(i), ref store7.GetByIndex(index7)  );
              }

              break;
          }
          case 6:
          {
              var dense = store7.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;
                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(i)  );
              }

              break;
          }
      }
  }
  public void QueryParallel<T1, T2, T3, T4, T5, T6, T7>(QueryDelegate<T1, T2, T3, T4, T5, T6, T7> action)
      where T1 : struct
      where T2 : struct
      where T3 : struct
      where T4 : struct
      where T5 : struct
      where T6 : struct
      where T7 : struct
  {
      var store1 = Assure<T1>();
      var store2 = Assure<T2>();
      var store3 = Assure<T3>();
      var store4 = Assure<T4>();
      var store5 = Assure<T5>();
      var store6 = Assure<T6>();
      var store7 = Assure<T7>();

      var leader = 0;
      var leaderCount = store1.Count;

      if (store2.Count < leaderCount)
      {
          leader = 1;
          leaderCount = store2.Count;
      }

      if (store3.Count < leaderCount)
      {
          leader = 2;
          leaderCount = store3.Count;
      }

      if (store4.Count < leaderCount)
      {
          leader = 3;
          leaderCount = store4.Count;
      }

      if (store5.Count < leaderCount)
      {
          leader = 4;
          leaderCount = store5.Count;
      }

      if (store6.Count < leaderCount)
      {
          leader = 5;
          leaderCount = store6.Count;
      }

      if (store7.Count < leaderCount)
      {
          leader = 6;
          leaderCount = store7.Count;
      }

      switch (leader)
      {
          case 0:
          {
              var dense = store1.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;
                  if (!store7.TryGetIndex(entity, out var index7)) return;

                  action(ref store1.GetByIndex(i), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7)  );
              });

              break;
          }
          case 1:
          {
              var dense = store2.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;
                  if (!store7.TryGetIndex(entity, out var index7)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(i), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7)  );
              });

              break;
          }
          case 2:
          {
              var dense = store3.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;
                  if (!store7.TryGetIndex(entity, out var index7)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(i), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7)  );
              });

              break;
          }
          case 3:
          {
              var dense = store4.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;
                  if (!store7.TryGetIndex(entity, out var index7)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(i), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7)  );
              });

              break;
          }
          case 4:
          {
              var dense = store5.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;
                  if (!store7.TryGetIndex(entity, out var index7)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(i), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7)  );
              });

              break;
          }
          case 5:
          {
              var dense = store6.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  if (!store7.TryGetIndex(entity, out var index7)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(i), ref store7.GetByIndex(index7)  );
              });

              break;
          }
          case 6:
          {
              var dense = store7.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;
                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(i)  );
              });

              break;
          }
      }
  }
  public delegate void QueryDelegate<T1, T2, T3, T4, T5, T6, T7, T8>(ref T1 c1, ref T2 c2, ref T3 c3, ref T4 c4, ref T5 c5, ref T6 c6, ref T7 c7, ref T8 c8)
      where T1 : struct
      where T2 : struct
      where T3 : struct
      where T4 : struct
      where T5 : struct
      where T6 : struct
      where T7 : struct
      where T8 : struct
;

  public void Query<T1, T2, T3, T4, T5, T6, T7, T8>(QueryDelegate<T1, T2, T3, T4, T5, T6, T7, T8> action)
      where T1 : struct
      where T2 : struct
      where T3 : struct
      where T4 : struct
      where T5 : struct
      where T6 : struct
      where T7 : struct
      where T8 : struct
  {
      var store1 = Assure<T1>();
      var store2 = Assure<T2>();
      var store3 = Assure<T3>();
      var store4 = Assure<T4>();
      var store5 = Assure<T5>();
      var store6 = Assure<T6>();
      var store7 = Assure<T7>();
      var store8 = Assure<T8>();

      var leader = 0;
      var leaderCount = store1.Count;

      if (store2.Count < leaderCount)
      {
          leader = 1;
          leaderCount = store2.Count;
      }

      if (store3.Count < leaderCount)
      {
          leader = 2;
          leaderCount = store3.Count;
      }

      if (store4.Count < leaderCount)
      {
          leader = 3;
          leaderCount = store4.Count;
      }

      if (store5.Count < leaderCount)
      {
          leader = 4;
          leaderCount = store5.Count;
      }

      if (store6.Count < leaderCount)
      {
          leader = 5;
          leaderCount = store6.Count;
      }

      if (store7.Count < leaderCount)
      {
          leader = 6;
          leaderCount = store7.Count;
      }

      if (store8.Count < leaderCount)
      {
          leader = 7;
          leaderCount = store8.Count;
      }

      switch (leader)
      {
          case 0:
          {
              var dense = store1.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;
                  if (!store7.TryGetIndex(entity, out var index7)) continue;
                  if (!store8.TryGetIndex(entity, out var index8)) continue;

                  action(ref store1.GetByIndex(i), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7), ref store8.GetByIndex(index8)  );
              }

              break;
          }
          case 1:
          {
              var dense = store2.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;
                  if (!store7.TryGetIndex(entity, out var index7)) continue;
                  if (!store8.TryGetIndex(entity, out var index8)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(i), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7), ref store8.GetByIndex(index8)  );
              }

              break;
          }
          case 2:
          {
              var dense = store3.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;
                  if (!store7.TryGetIndex(entity, out var index7)) continue;
                  if (!store8.TryGetIndex(entity, out var index8)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(i), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7), ref store8.GetByIndex(index8)  );
              }

              break;
          }
          case 3:
          {
              var dense = store4.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;
                  if (!store7.TryGetIndex(entity, out var index7)) continue;
                  if (!store8.TryGetIndex(entity, out var index8)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(i), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7), ref store8.GetByIndex(index8)  );
              }

              break;
          }
          case 4:
          {
              var dense = store5.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;
                  if (!store7.TryGetIndex(entity, out var index7)) continue;
                  if (!store8.TryGetIndex(entity, out var index8)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(i), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7), ref store8.GetByIndex(index8)  );
              }

              break;
          }
          case 5:
          {
              var dense = store6.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  if (!store7.TryGetIndex(entity, out var index7)) continue;
                  if (!store8.TryGetIndex(entity, out var index8)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(i), ref store7.GetByIndex(index7), ref store8.GetByIndex(index8)  );
              }

              break;
          }
          case 6:
          {
              var dense = store7.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;
                  if (!store8.TryGetIndex(entity, out var index8)) continue;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(i), ref store8.GetByIndex(index8)  );
              }

              break;
          }
          case 7:
          {
              var dense = store8.Set.Dense;

              for (int i = 0; i < leaderCount; i++)
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) continue;
                  if (!store2.TryGetIndex(entity, out var index2)) continue;
                  if (!store3.TryGetIndex(entity, out var index3)) continue;
                  if (!store4.TryGetIndex(entity, out var index4)) continue;
                  if (!store5.TryGetIndex(entity, out var index5)) continue;
                  if (!store6.TryGetIndex(entity, out var index6)) continue;
                  if (!store7.TryGetIndex(entity, out var index7)) continue;
                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7), ref store8.GetByIndex(i)  );
              }

              break;
          }
      }
  }
  public void QueryParallel<T1, T2, T3, T4, T5, T6, T7, T8>(QueryDelegate<T1, T2, T3, T4, T5, T6, T7, T8> action)
      where T1 : struct
      where T2 : struct
      where T3 : struct
      where T4 : struct
      where T5 : struct
      where T6 : struct
      where T7 : struct
      where T8 : struct
  {
      var store1 = Assure<T1>();
      var store2 = Assure<T2>();
      var store3 = Assure<T3>();
      var store4 = Assure<T4>();
      var store5 = Assure<T5>();
      var store6 = Assure<T6>();
      var store7 = Assure<T7>();
      var store8 = Assure<T8>();

      var leader = 0;
      var leaderCount = store1.Count;

      if (store2.Count < leaderCount)
      {
          leader = 1;
          leaderCount = store2.Count;
      }

      if (store3.Count < leaderCount)
      {
          leader = 2;
          leaderCount = store3.Count;
      }

      if (store4.Count < leaderCount)
      {
          leader = 3;
          leaderCount = store4.Count;
      }

      if (store5.Count < leaderCount)
      {
          leader = 4;
          leaderCount = store5.Count;
      }

      if (store6.Count < leaderCount)
      {
          leader = 5;
          leaderCount = store6.Count;
      }

      if (store7.Count < leaderCount)
      {
          leader = 6;
          leaderCount = store7.Count;
      }

      if (store8.Count < leaderCount)
      {
          leader = 7;
          leaderCount = store8.Count;
      }

      switch (leader)
      {
          case 0:
          {
              var dense = store1.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;
                  if (!store7.TryGetIndex(entity, out var index7)) return;
                  if (!store8.TryGetIndex(entity, out var index8)) return;

                  action(ref store1.GetByIndex(i), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7), ref store8.GetByIndex(index8)  );
              });

              break;
          }
          case 1:
          {
              var dense = store2.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;
                  if (!store7.TryGetIndex(entity, out var index7)) return;
                  if (!store8.TryGetIndex(entity, out var index8)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(i), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7), ref store8.GetByIndex(index8)  );
              });

              break;
          }
          case 2:
          {
              var dense = store3.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;
                  if (!store7.TryGetIndex(entity, out var index7)) return;
                  if (!store8.TryGetIndex(entity, out var index8)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(i), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7), ref store8.GetByIndex(index8)  );
              });

              break;
          }
          case 3:
          {
              var dense = store4.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;
                  if (!store7.TryGetIndex(entity, out var index7)) return;
                  if (!store8.TryGetIndex(entity, out var index8)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(i), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7), ref store8.GetByIndex(index8)  );
              });

              break;
          }
          case 4:
          {
              var dense = store5.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;
                  if (!store7.TryGetIndex(entity, out var index7)) return;
                  if (!store8.TryGetIndex(entity, out var index8)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(i), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7), ref store8.GetByIndex(index8)  );
              });

              break;
          }
          case 5:
          {
              var dense = store6.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  if (!store7.TryGetIndex(entity, out var index7)) return;
                  if (!store8.TryGetIndex(entity, out var index8)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(i), ref store7.GetByIndex(index7), ref store8.GetByIndex(index8)  );
              });

              break;
          }
          case 6:
          {
              var dense = store7.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;
                  if (!store8.TryGetIndex(entity, out var index8)) return;

                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(i), ref store8.GetByIndex(index8)  );
              });

              break;
          }
          case 7:
          {
              var dense = store8.Set.Dense;

              Parallel.For(0, leaderCount, i =>
              {
                  var entity = dense[i];

                  if (!store1.TryGetIndex(entity, out var index1)) return;
                  if (!store2.TryGetIndex(entity, out var index2)) return;
                  if (!store3.TryGetIndex(entity, out var index3)) return;
                  if (!store4.TryGetIndex(entity, out var index4)) return;
                  if (!store5.TryGetIndex(entity, out var index5)) return;
                  if (!store6.TryGetIndex(entity, out var index6)) return;
                  if (!store7.TryGetIndex(entity, out var index7)) return;
                  action(ref store1.GetByIndex(index1), ref store2.GetByIndex(index2), ref store3.GetByIndex(index3), ref store4.GetByIndex(index4), ref store5.GetByIndex(index5), ref store6.GetByIndex(index6), ref store7.GetByIndex(index7), ref store8.GetByIndex(i)  );
              });

              break;
          }
      }
  }
}
