<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Configurations>Debug;Release;Publish</Configurations>
	</PropertyGroup>
	<ItemGroup>
		<Compile Include="TinyECS\QueryGenerator.csx" />
	</ItemGroup>
	<ItemGroup>
		<Compile Remove="**/*.csx" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Hexa.NET.ImGui" Version="2.2.9" />
		<PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5">
			<PrivateAssets>All</PrivateAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<Content Include="Libs\Windows\*.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>%(Filename)%(Extension)</TargetPath>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\TinyFmod\TinyFmod.csproj" />
	</ItemGroup>
	<PropertyGroup Condition="'$(PublishDir)' == ''">
		<DefineConstants>$(DefineConstants);EDITOR_BUILD</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(PublishDir)' != ''">
		<DefineConstants>$(DefineConstants);PUBLISH</DefineConstants>
	</PropertyGroup>

	<PropertyGroup>
		<EditorGeneratedPath>$(MSBuildProjectDirectory)\Editor\EditorProjectPath.g.cs</EditorGeneratedPath>
	</PropertyGroup>

	<Target Name="GenerateEditorProjectPath" BeforeTargets="CoreCompile">
		<MakeDir Directories="$(MSBuildProjectDirectory)\Editor" />

		<WriteLinesToFile
			File="$(EditorGeneratedPath)"
			Overwrite="true"
			Lines="namespace Darkrit.Editor%3B; internal static class EditorProjectPath { public const string Root = @&quot;$(MSBuildProjectDirectory)&quot;%3B }" />

		<ItemGroup>
			<Compile Include="$(EditorGeneratedPath)" />
		</ItemGroup>
	</Target>
</Project>